---
title: "Test"
author: "Brice Nocenti"
date: February 17, 2024
output: 
  rmdformats::downcute:
    df_print: kable
    code_folding: hide
---

<!--   rmdformats::downcute: -->

<!-- html_document: -->
<!-- highlight: tango -->

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE, warning = FALSE, message = FALSE
)

source("~\\github/socio_public_services/publications/2024_OrgaTravailAdminPub/Demarrage.R", encoding = "UTF-8")
# options("tabxplor.output_kable" = TRUE) # options("tabxplor.kable_popover" = TRUE)
# options(tabxplor.color_style_theme = "dark")

ct <- readRDS("~\\Data\\Conditions de travail\\ct.rds")

# Ajouter classification ascendante hiérarchique (CAH) sauvegardée : variable cah_orga
ct <- ct |> left_join(readRDS("~\\github/socio_public_services/publications\\2024_OrgaTravailAdminPub\\cah_orga_final.rds"), by = "ID") 

# Variables logiques pour délimiter le champ
salariat05 <- ct$CHAMP_CT2005 == "1-Champ 2005" & ct$ANNEE %in% c("2005", "2013", "2019") & 
  !ct$EMP %in% c("8-Particuliers", "I-Pas d'employeur", "I-Pas d’employeur") & !is.na(ct$EMP) &
  !is.na(ct$pondcal)

`2005` <- ct$ANNEE == "2005"
`2013` <- ct$ANNEE == "2013"
`2016` <- ct$ANNEE == "2016"
`2019` <- ct$ANNEE == "2019"

# Champs et sources
champ05  <- "Champ : salarié·es des organisations, France métropolitaine. Pourcentages pondérés."

source0519 <- "Source : Dares-Drees-DGAFP, enquête Conditions de travail 2005, 2013 et 2019, volet actifs occupés (diffusion Adisp)."

source19 <- "Source : Dares-Drees-DGAFP, enquête Conditions de travail 2019, volet actifs occupés (diffusion Adisp)."


# Derniers ajustements des noms de catégories
ct <- ct |> mutate(SEXE = fct_rev(SEXE) )
ct <- ct |> mutate(PPP1 = fct_relevel(PPP1, "1-Chefs d’entreprise", "2-Cadres", "4-Professions organisées") )

ct <- ct |> mutate(
  EMP5_ETAT_GES = fct_recode(EMP5_ETAT_GES,
                             "11-État/HP" = "11-État_HP"                        ,
                             "12-GES"     = "12-Grandes entreprises de services" )
)

ct <- ct |> 
  mutate(EMP4 = fct_relevel(EMP4, "11-État", "12-Grandes entreprises de services", "30-Grande industrie"))

ct <- ct|> mutate(NOUVELLE =  fct_recode(
  NOUVELLE,
  "1-Apprendre des choses"                  = "1-Apprendre des choses",
  "2-Ne pas apprendre des choses nouvelles" = "2-Pas apprendre"
))


ct <- ct |> mutate(COMMENT = fct_relevel(COMMENT, sort))


```




### TABLEAU 7 – Les formes d’organisation et les objectifs chiffrés des cadres des administrations publiques en 2019
```{r tab7, echo = TRUE}

orga_cadres_subtext <- 
  c("Lecture : 13 % des inspecteurs et inspectrices des Finances publiques sont dans la classe d’organisation « autonomie du métier ». HP = hôpitaux publics ; CL = collectivités locales ; EN = Éducation nationale. Nuances de bleu : proportion significativement supérieure à la moyenne (Total de colonne) après prise en compte de la marge d’erreur (intervalle de Wald avec ajustement d’Agresti et Caffo, seuil de confiance à 95 %). Nuances du jaune au rouge : proportion significativement inférieure à la moyenne. En gris : proportion non significativement différente de la moyenne.",
    "Champ : cadres des administrations publiques, France métropolitaine. Pourcentages pondérés.",
    source19)

orga_cadres_tab <- 
  ct[salariat05 & `2019` & ct$EMP_ADM_ENT == "1-Administrations publiques" & ct$PPP1 == "2-Cadres", ] |>
  mutate(PPP2adm = fct_cross(PPP2, EMP) |>
           fct_relabel(~ str_replace(., "^(...)-([^:]+):(.)-(.+)", "\\1\\3-\\2 \\4") |>
                         str_replace("(?<=^...)1", "4") |>
                         str_replace("(?<=^...)2", "1") |>
                         str_replace("(?<=^...)3", "2") |>
                         str_replace("(?<=^...)4", "3") |>
                         str_replace("Hôpitaux publics", "HP") |>
                         str_replace("Collectivités locales", "CL")
           ),
         PPP2 = as.factor(if_else(FAPPP %in% c("D-Filière administrative", "E-Filière technique"),
                                  true  = as.character(PPP2adm),
                                  false = str_replace(as.character(PPP2), "^(...)-", "\\10-")
                                  
         )) |>
           fct_relabel(~ str_remove(., "Cadres banque") |> str_remove(", +$") ) |>
           fct_relabel(~ str_replace(., "^(.)(.)(.)(.)", "\\4\\2\\1\\3") ) |>
           fct_recode("2F20-Cadres de santé ♀" = "0F20-Cadres de santé ♀") |> 
           fct_relevel(sort),
         
         grouping = str_sub(PPP2, 1, 1) |> str_replace("0", "1") |> as.factor()
  ) |>
  tab(PPP2, cah_ORGA, grouping, sup_cols = OBJECTIF,
      wt = pondcal, pct = "row", na = "drop", color = "after_ci", 
      cleannames = TRUE, subtext = orga_cadres_subtext
  ) |>
  mutate(n = mutate(Total, display = "n")) |>
  filter(!(is_totrow(Total) & grouping != "Ensemble")) |> 
  filter(n >= 20) |>
  group_by(grouping)
# orga_cadres_tab |> tab_xl(colwidth = 10, sheets = "unique")

orga_cadres_tab |> tab_kable()
```

